serviceworker:
  enabled: false
metatags:
  jsonld:
    enabled: false
body:
  images:
    caption:
      enabled: true
    resize:
      enabled: false
    responsive:
      enabled: false
    webp:
      enabled: false
assets:
  images:
    optimize:
      enabled: false
    responsive:
      enabled: false
    webp:
      enabled: false
